#!/usr/bin/env python3

# Copyright 2006-2025 Roy Hills
#
# This file is part of arp-scan.
#
# arp-scan is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# arp-scan is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with arp-scan.  If not, see <http://www.gnu.org/licenses/>.
#
# get-oui -- Fetch the MAC/Vendor registry data from the IEEE website
#
# Author: Roy Hills
# Date: 16 March 2006
#
# This script downloads the Ethernet MAC/Vendor registry data from the
# IEEE website, and converts it to the format used by arp-scan.
#
# Python port -- get-oui.py
#
# Author: sonikbhoom
# Date:  14 April 2026

import csv
import sys
import os
import argparse
import requests
from datetime import datetime
from io import StringIO

# Configuration
IEEE_REG_URLS = {
    "OUI": "https://standards-oui.ieee.org/oui/oui.csv",
    "MAM": "https://standards-oui.ieee.org/oui28/mam.csv",
    "OUI36": "https://standards-oui.ieee.org/oui36/oui36.csv",
    "IAB": "https://standards-oui.ieee.org/iab/iab.csv"
}
DEFAULT_FILENAME = 'ieee-oui.txt'

def main():
    # 1. Process Options
    parser = argparse.ArgumentParser(
        description="Fetch Ethernet MAC-Vendor registry data from IEEE and save for arp-scan.",
        add_help=False
    )
    parser.add_argument("-h", action="help", help="Display this usage message.")
    parser.add_argument("-f", dest="filename", default=DEFAULT_FILENAME, help="Specify output file.")
    parser.add_argument("-v", action="store_true", dest="verbose", help="Give verbose progress messages.")
    
    args = parser.parse_args()
    filename = args.filename
    verbose = args.verbose

    # 2. Handle Backup
    if os.path.isfile(filename):
        backup = f"{filename}.bak"
        if verbose:
            print(f"Renaming {filename} to {backup}")
        try:
            os.replace(filename, backup)
        except OSError:
            sys.exit(f"Could not rename {filename} to {backup}")

    # 3. Open Output File
    if verbose:
        print(f"Opening {filename} for output")
    
    try:
        with open(filename, 'w', encoding='utf-8') as output_file:
            # Write Header
            date_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            header = (
                f"# ieee-oui.txt -- IEEE Ethernet OUI-Vendor mapping file for arp-scan\n"
                f"# Generated by get-oui.py at {date_string}"
"""
#
# This file contains the IEEE Ethernet MAC address registry entries that are
# used to determine the Ethernet vendor for a given MAC address.
#
# Each line of this file contains an OUI-vendor mapping in the form:
#
# <MAC-Prefix><TAB><Vendor>
#
# Where <MAC-Prefix> is the prefix of the MAC address in hex, and <Vendor>
# is the name of the vendor.  The prefix can be of any length from two hex
# digits (one octet) to twelve hex digits (six octets, the entire Ethernet
# hardware address).
#
# The order of entries in this file are not important.
#
# arp-scan will attempt to match larger prefixes before trying to match
# smaller ones, and will stop at the first match.
#
# Blank lines and lines beginning with "#" are ignored.
#
# This file was automatically generated by get-oui at $date_string
#
# Do not edit this file.  If you want to add additional MAC-Vendor mappings,
# edit the file mac-vendor.txt instead.
"""
            )
            output_file.write(header)

            total_entries = 0
            
            # 4. Fetch and Process each Registry
            # Sorting keys to match Perl's 'sort keys' behavior
            for key in sorted(IEEE_REG_URLS.keys()):
                url = IEEE_REG_URLS[key]
                if verbose:
                    print(f"Processing IEEE {key} registry data from {url}")

                headers = {
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36'
                }
                
                try:
                    response = requests.get(url, headers=headers)
                    response.raise_for_status()
                except requests.exceptions.RequestException as e:
                    sys.exit(f"Error fetching {url}: {e}")

                content = response.text
                if not content:
                    sys.exit(f"Zero-sized response from {url}")

                if verbose:
                    print(f"\tDownloaded {len(content.encode('utf-8'))} bytes")

                # Parse CSV
                output_file.write(f"#\n# Start of IEEE {key} registry data\n#\n")
                
                f_in = StringIO(content)
                reader = csv.reader(f_in)
                
                # Skip header row (Registry, Assignment, Organization Name, Organization Address)
                next(reader, None)
                
                lineno = 0
                for row in reader:
                    if len(row) >= 3:
                        mac = row[1]
                        vendor = row[2].strip()
                        output_file.write(f"{mac}\t{vendor}\n")
                        lineno += 1
                
                output_file.write(f"#\n# End of IEEE {key} registry data. {lineno} entries.\n#\n")
                if verbose:
                    print(f"\t{lineno} {key} entries written to {filename}")
                total_entries += lineno

        print(f"\nTotal of {total_entries} MAC/Vendor mappings written to {filename}")

    except IOError as e:
        sys.exit(f"Error writing to file {filename}: {e}")

if __name__ == "__main__":
    main()
