#!/usr/bin/env python3
import csv
import sys
import os
import argparse
import requests
from datetime import datetime
from io import StringIO

# Configuration
IEEE_REG_URLS = {
    "OUI": "https://standards-oui.ieee.org/oui/oui.csv",
    "MAM": "https://standards-oui.ieee.org/oui28/mam.csv",
    "OUI36": "https://standards-oui.ieee.org/oui36/oui36.csv",
    "IAB": "https://standards-oui.ieee.org/iab/iab.csv"
}
DEFAULT_FILENAME = 'ieee-oui.txt'

def main():
    # 1. Process Options
    parser = argparse.ArgumentParser(
        description="Fetch Ethernet MAC-Vendor registry data from IEEE and save for arp-scan.",
        add_help=False
    )
    parser.add_argument("-h", action="help", help="Display this usage message.")
    parser.add_argument("-f", dest="filename", default=DEFAULT_FILENAME, help="Specify output file.")
    parser.add_argument("-v", action="store_true", dest="verbose", help="Give verbose progress messages.")
    
    args = parser.parse_args()
    filename = args.filename
    verbose = args.verbose

    # 2. Handle Backup
    if os.path.isfile(filename):
        backup = f"{filename}.bak"
        if verbose:
            print(f"Renaming {filename} to {backup}")
        try:
            os.replace(filename, backup)
        except OSError:
            sys.exit(f"Could not rename {filename} to {backup}")

    # 3. Open Output File
    if verbose:
        print(f"Opening {filename} for output")
    
    try:
        with open(filename, 'w', encoding='utf-8') as output_file:
            # Write Header
            date_string = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            header = (
                f"# ieee-oui.txt -- IEEE Ethernet OUI-Vendor mapping file for arp-scan\n"
                f"# Generated by get-oui.py at {date_string}\n"
                "# Format: <MAC-Prefix>\\t<Vendor>\n#\n"
            )
            output_file.write(header)

            total_entries = 0
            
            # 4. Fetch and Process each Registry
            # Sorting keys to match Perl's 'sort keys' behavior
            for key in sorted(IEEE_REG_URLS.keys()):
                url = IEEE_REG_URLS[key]
                if verbose:
                    print(f"Processing IEEE {key} registry data from {url}")

                headers = {
                    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Safari/537.36'
                }
                
                try:
                    response = requests.get(url, headers=headers)
                    response.raise_for_status()
                except requests.exceptions.RequestException as e:
                    sys.exit(f"Error fetching {url}: {e}")

                content = response.text
                if not content:
                    sys.exit(f"Zero-sized response from {url}")

                if verbose:
                    print(f"\tDownloaded {len(content.encode('utf-8'))} bytes")

                # Parse CSV
                output_file.write(f"\n#\n# Start of IEEE {key} registry data\n#\n")
                
                f_in = StringIO(content)
                reader = csv.reader(f_in)
                
                # Skip header row (Registry, Assignment, Organization Name, Organization Address)
                next(reader, None)
                
                lineno = 0
                for row in reader:
                    if len(row) >= 3:
                        mac = row[1]
                        vendor = row[2].strip()
                        output_file.write(f"{mac}\t{vendor}\n")
                        lineno += 1
                
                output_file.write(f"#\n# End of IEEE {key} registry data. {lineno} entries.\n#\n")
                if verbose:
                    print(f"\t{lineno} {key} entries written to {filename}")
                total_entries += lineno

        print(f"\nTotal of {total_entries} MAC/Vendor mappings written to {filename}")

    except IOError as e:
        sys.exit(f"Error writing to file {filename}: {e}")

if __name__ == "__main__":
    main()
